name: Build and Publish Images to Docker Hub

on:
    push:
        branches: "*"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Extract Branch Name
              shell: bash
              run: echo "branch=${GITHUB_REF/refs\/heads\//}" >> $GITHUB_OUTPUT
              id: extract_branch

            - name: Output Docker Tag
              shell: bash
              run: echo "docker_tag=accountingnerd/suitecloud-cli:${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_OUTPUT
              id: get_docker_tag

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ${{ steps.get_docker_tag.outputs.docker_tag }}
